app/models/prediccion.py
from main import db #Cargamos la instacia db

class Prediccion(db.Model):
    id = db.Column(db.Integer, primary_key=True)                                #Definimos el atributo id como llave primaria
    porcentaje_perro = db.Column(db.String(20))                                  #Definimos el atributo para la predicción de leon
    porcentaje_lobo = db.Column(db.String(20))                                  #Definimos el atributo para el predicción de gato
    porcentaje_zorro = db.Column(db.String(20))                                 #Definimos el atributo para la predicción de tigre
    porcentaje_coyote= db.Column(db.String(20))                                #Definimos el atributo para el predicción de pantera
    imagen_prediccion = db.Column(db.String(500))                               #Definimos el atributo para la imagen de la predicción
    id_usuario_fk = db.Column(db.Integer, db.ForeignKey('usuario.id'))          #Definimos el atributo para el id del usuario con llave foranea

    #Definimos el constructor para pasar los datos a la bd
    def __init__(self, porcentaje_perro, porcentaje_lobo, porcentaje_zorro, porcentaje_coyote, imagen_prediccion, id_usuario_fk):
        self.porcentaje_perro = porcentaje_perro                                                        #Asignamos el valor proporcionado al atributo porcentaje_leon
        self.porcentaje_lobo = porcentaje_lobo                                                        #Asignamos el valor proporcionado al atributo porcentaje_gato
        self.porcentaje_zorro = porcentaje_zorro                                                      #Asignamos el valor proporcionado al atributo porcentaje_tigre
        self.porcentaje_coyote = porcentaje_coyote                                                  #Asignamos el valor proporcionado al atributo porcentaje_pantera
        self.imagen_prediccion = imagen_prediccion                                                   #Asignamos el valor proporcionado al atributo imagen_prediccion
        self.id_usuario_fk = id_usuario_fk                                                       #Asignamos el valor proporcionado al atributo id_usuario_fk

app/controllers/prediccion_controller.py
from flask import request, redirect, render_template, session, url_for, current_app, flash
from random import sample
from werkzeug.utils import secure_filename   
import os
import numpy as np
import json
from scipy.special import softmax
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from keras.models import load_model
from models.prediccion import Prediccion                              #Cargamos la clase Prediccion
from main import db  


#Definimos una función para generar un string aleatorio
def stringAleatorio():
    #Definimos el string
    string_aleatorio = "0123456789abcdefghijklmnopqrstuvwxyz_"

    #Definimos la longitud
    longitud         = 20

    #Convertimos el string a mayusculas
    secuencia        = string_aleatorio.upper()

    #Generamos un resultado aleatorio
    resultado_aleatorio  = sample(secuencia, longitud)

    #Unimos el string aleatorio
    string_aleatorio     = "".join(resultado_aleatorio)

    #Retornamos el string aleatorio
    return string_aleatorio

#Definimos una función para la predicción del modelo
def realizar_prediccion(ruta_imagen):
    longitud, altura = 256, 256 #para caninos

    # Definimos la ruta del modelo
    ruta_base = os.path.dirname(os.path.abspath(__file__))
    ruta_modelo = os.path.join(ruta_base, '../../src/Modelo_entrenado/modelo_caninos.h5')

    #Cargamos el modelo
    modelo_cargado = load_model(ruta_modelo)

    #Definimos la ruta del archivo JSON
    ruta_json = os.path.join(ruta_base, '../../src/Modelo_entrenado/clases_Canino.json')

    #Cargamos el archivo JSON con el mapeo de clases
    with open(ruta_json, 'r') as f:
        mapeo_clases = json.load(f)
        print(mapeo_clases) #Imprimimos el contenido del json para observar las clases

    #Ajustamos el tamaño de la imagen
    imagen = load_img(ruta_imagen, target_size=(altura, longitud))

    #Convertimos la imagen a un array de NumPy
    imagen_array = img_to_array(imagen)
    imagen_array = np.expand_dims(imagen_array, axis=0)

    #Hacemos la predicción con el modelo
    prediccion = modelo_cargado.predict(imagen_array)

    #Obtenemos las probabilidades de pertenencia a cada clase aplicando la función softmax
    probabilidades = softmax(prediccion)[0]

    #Obtenemos los nombres de las clases
    nombre_clases = list(mapeo_clases.keys())

    #Definimos una lista vacía para almacenar las predicciones
    lista_prediccion = []

    #Imprimimos los porcentajes de pertenencia a cada clase
    for i, name in enumerate(nombre_clases):
        #Realizamos el cálculo del porcentaje para cada clase
        porcentaje = round(probabilidades[i] * 100, 2)

        #Agregamos el porcentaje a la lista de predicciones
        lista_prediccion.append(porcentaje)

    #Retornamos la lista
    return lista_prediccion

#Definimos una función para la predicción
def guardar_prediccion():
    try:
        #Obtenemos la imagen enviada desde el formulario
        imagen = request.files['imagen']

        #Nombre original de la imagen
        nombre_original = secure_filename(imagen.filename)

        #Capturando las extensiones de la imagen
        extension_imagen = os.path.splitext(nombre_original)[1]

        #Establecemos un nuevo nombre para la imagen
        nuevo_nombre_imagen = stringAleatorio() + extension_imagen

        #Guardamos la imagen en la carpeta definida
        ruta_img = os.path.join(current_app.root_path, 'static', 'img', nuevo_nombre_imagen)

        #Guardamos la imagen en la ruta dada
        imagen.save(ruta_img)

        #Llamamos la función para realizar la predicción
        lista_prediccion = realizar_prediccion(ruta_img)

        #Obtenemos el porcentaje de predicción para cada variable
        porcentaje_coyote = lista_prediccion[0]
        porcentaje_lobo = lista_prediccion[1]
        porcentaje_perro = lista_prediccion[2]
        porcentaje_zorro = lista_prediccion[3]

        #Obtenemos el id del usuario de la sesión
        id_usuario_fk = session['id_usuario']

        #Creamos una nueva instancia de Prediccion con los datos proporcionados
        prediccion = Prediccion(porcentaje_perro, porcentaje_lobo, porcentaje_zorro, porcentaje_coyote, ruta_img, id_usuario_fk)

        #Guardamos la nueva predicción
        db.session.add(prediccion)

        #Finalizamos la conexión para que guarde el nuevo usuario a la bd
        db.session.commit()

        #Renderizamos el template y cada predicción de clase
        return render_template('prediccion.html', 
                            porcentaje_coyote=porcentaje_coyote, 
                            porcentaje_lobo=porcentaje_lobo, 
                            porcentaje_perro=porcentaje_perro, 
                            porcentaje_zorro=porcentaje_zorro,
                            ruta_img=url_for('static', filename=f'img/{nuevo_nombre_imagen}'))
    
    except Exception as e:
        #Redireccionamos a la ruta de prediccion de felinos
        return redirect('/prediccion/felinos')

#Definimos una función para todas las predicciones del usuario
def obtener_predicciones():
    try:
        #Verificamos si en sesiones hay un id del usuario
        if not 'id_usuario' in session:
            #Mostramos una alerta con SweetAlert2
            flash('Primero debe de autenticarse.', 'error')

            #Redireccionamos a la ruta del login
            return redirect('/login')
        
        #Obtenemos el id del usuario de la sesión
        id_usuario_fk = session['id_usuario']

        #Buscamos todas las predicciones del usuario
        usuario_predicciones = Prediccion.query.filter_by(id_usuario_fk=id_usuario_fk).all()

        #Verificamos si se encontró un usuario
        if usuario_predicciones:
            #Obtenemos el nombre de archivo de la imagen en cada predicción
            for prediccion in usuario_predicciones:
                nombre_imagen = os.path.basename(prediccion.imagen_prediccion)
                prediccion.imagen_prediccion = url_for('static', filename=f'img/{nombre_imagen}')
            
            #Renderizamos el template perfil.html y pasamos los datos del usuario
            return render_template('ver_predicciones.html', predicciones=usuario_predicciones)

    except Exception as e:
        #Redireccionamos a la ruta del login
        return redirect('/prediccion/felinos')

app/routes/prediccion.py
from flask import Blueprint 
from controllers.autenticacion_controller import verificar_sesion_pred           #Cargamos la función verificar_sesion_pred del controlador
from controllers.prediccion_controller import guardar_prediccion                 #Cargamos la función guardar_prediccion del controlador
from controllers.prediccion_controller import obtener_predicciones               #Cargamos la función obtener_predicciones del controlador

#Creamos la sección para las rutas de predicción
rutas_prediccion = Blueprint('prediccion', __name__)

#Configuramos la ruta para la predicción
@rutas_prediccion.route('/prediccion/felinos')
def prediccion():
    #Retornamos la función verificar_sesion_pred
    return verificar_sesion_pred()

#Configuramos la ruta para guardar los datos del usuario
@rutas_prediccion.route('/prediccion/nueva_prediccion', methods=['POST'])
def nueva_prediccion():
    #Retornamos la función para guardar la nueva prediccion a la bd
    return guardar_prediccion()

#Configuramos la ruta para ver todas las predicciones del usuario
@rutas_prediccion.route('/prediccion/ver')
def datos_predicciones():
    #Retornamos la función obtener_usuario
    return obtener_predicciones()

app/routes/usuario.py
from flask import Blueprint, render_template, redirect
from controllers.usuario_controller import guardar_usuario                  #Cargamos la función guardar_usuario del controlador
from controllers.autenticacion_controller import validar_credenciales       #Cargamos la función validar_credenciales del controlador
from controllers.usuario_controller import obtener_usuario                  #Cargamos la función obtener_usuario del controlador
from controllers.autenticacion_controller import logout_usuario             #Cargamos la función logout_user del controlador

#Creamos la sección para las rutas de usuarios
rutas_usuario = Blueprint('usuario', __name__)

#Configuramos la ruta raíz para redirigir al login
@rutas_usuario.route('/')
def root():
    return redirect('/login')

#Configuramos la ruta para el login
@rutas_usuario.route('/login')
def login():
    #Renderizamos el template login
    return render_template('login.html')

#Configuramos la ruta para la validación de credenciales
@rutas_usuario.route('/login/validar_usuario', methods=['POST'])
def validar_usuario():
    #Retornamos la función para validar credenciales del login
    return validar_credenciales()

#Configuramos la ruta para el registro de usuarios
@rutas_usuario.route('/registro/usuario')
def registro():
    #Renderizamos el template registro
    return render_template('registro.html')

#Configuramos la ruta para guardar los datos del usuario
@rutas_usuario.route('/registro/nuevo_usuario', methods=['POST'])
def nuevo_usuario():
    #Retornamos la función para guardar el usuario en la db
    return guardar_usuario()

#Configuramos la ruta para ver el perfil del usuario
@rutas_usuario.route('/usuario/perfil')
def perfil_usuario():
    #Retornamos la función obtener_usuario
    return obtener_usuario()

#Configuramos la ruta para cerrar sesión
@rutas_usuario.route('/usuario/logout')
def cerrar_sesion():
    #Retornamos la función logout_usuario
    return logout_usuario()

app/templates/login.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
        {% include 'partials/_sweetAlert2.html' %} <!-- incluimos las etiquetas necesarias para utilzar sweetAlert2 -->
    </head>
    <body>
        <div class="container">
            <h2>Iniciar sesión</h2>
            <form action="/login/validar_usuario" method="POST">
                <!-- Campos para iniciar sesión -->
                <input type="email" name="correo" placeholder="Correo electrónico" required>
                <input type="password" name="password" placeholder="Contraseña" required>
                <button type="submit">Iniciar Sesión</button>
            </form>
            <p>¿No tienes una cuenta? <a href="{{ url_for('usuario.registro') }}">Regístrate</a></p>
        </div>

        <!-- Obtenemos el mensaje enviado desde el controlador -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <script>
                    //Guardamos el mensaje para utilizarlo en otro js
                    var mensaje_error = "{{ messages[0] }}";
                </script>
                <script src="{{ url_for('static', filename='js/alerta_error.js') }}"></script>
            {% endif %}
        {% endwith %}
    </body>
</html>

app/templates/perfil.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Perfil</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/perfil.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
    </head>
    <body>
        {% include 'partials/_navbar.html' %}

        <div class="container">
            <h1>Perfil de Usuario</h1>
            <form>
                <div class="form-group">
                    <label for="nombre">Nombre:</label>
                    <input type="text" id="nombre" name="nombre" value="{{ usuario.nombre }}" readonly>
                </div>
                <div class="form-group">
                    <label for="apellido">Apellido:</label>
                    <input type="text" id="apellido" name="apellido" value="{{ usuario.apellido }}" readonly>
                </div>
                <div class="form-group">
                    <label for="direccion">Dirección:</label>
                    <input type="text" id="direccion" name="direccion" value="{{ usuario.direccion }}" readonly>
                </div>
                <div class="form-group">
                    <label for="correo">Correo:</label>
                    <input type="email" id="correo" name="correo" value="{{ usuario.correo }}" readonly>
                </div>
            </form>
        </div>
    </body>
</html>

app/templates/prediccion.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Predicción</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/prediccion.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
        {% include 'partials/_sweetAlert2.html' %} <!-- incluimos las etiquetas necesarias para utilzar sweetAlert2 -->
    </head>
    <body>
        {% include 'partials/_navbar.html' %}

        <div class="container">
            <h2>Reconocimiento de imágenes con IA</h2>
            {% if not ruta_img %}
                <div class="contenedor-imagen">
                    <form action="/prediccion/nueva_prediccion" method="POST" enctype="multipart/form-data">
                        <!-- Campo para subir imagen -->
                        <div class="contenedor-input">
                            <label for="imagen-input" class="imagen-label">Inserte Imagen</label>
                            <input id="imagen-input" type="file" name="imagen" accept=".png, .jpg, .jpeg" required>
                            <!-- <img id="imagen-miniatura" src="#" alt="Miniatura de la imagen" /> -->
                        </div>
                        <button id="btnPredecir" type="submit">Realizar predicción</button>
                    </form>
                </div>
            {% endif %}
            {% if ruta_img %}
                <div class="contenedor-imagen">
                    <div>
                        <img src="{{ ruta_img }}" alt="Predicción de la imagen" id="imagen-miniatura">
                    </div>
                </div>
            {% endif %}

            <div class="contenedor-prediccion">
                <h3>Resultado:</h3>
                <div class="prediccion-item">
                    <label for="coyote-input">Coyote</label>
                    <div class="prediccion-nivel">
                        <span id="nivel_coyote" class="nivel"></span>
                    </div>
                    <span id="coyote" class="prediccion-porcentaje">{{ porcentaje_coyote }}%</span>
                </div>
                <div class="prediccion-item">
                    <label for="lobo-input">Lobo</label>
                    <div class="prediccion-nivel">
                        <span id="nivel_lobo" class="nivel"></span>
                    </div>
                    <span id="lobo" class="prediccion-porcentaje">{{ porcentaje_lobo }}%</span>
                </div>
                <div class="prediccion-item">
                    <label for="perro-input">Perro</label>
                    <div class="prediccion-nivel">
                        <span id="nivel_perro" class="nivel"></span>
                    </div>
                    <span id="perro" class="prediccion-porcentaje">{{ porcentaje_perro }}%</span>
                </div>
                <div class="prediccion-item">
                    <label for="zorro-input">Zorro</label>
                    <div class="prediccion-nivel">
                        <span id="nivel_zorro" class="nivel"></span>
                    </div>
                    <span id="zorro" class="prediccion-porcentaje">{{ porcentaje_zorro }}%</span>
                </div>
            </div>
        </div>
    </body>
    <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
    <script src="{{ url_for('static', filename='js/predecir.js') }}"></script>
</html>

app/templates/registro.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registro</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/registro.css') }}">
        {% include 'partials/_sweetAlert2.html' %} <!-- incluimos las etiquetas necesarias para utilzar sweetAlert2 -->
    </head>
    <body>
        <div class="container">
            <h2>Registro de usuario</h2>
            <form action="/registro/nuevo_usuario" method="POST">
                <!-- Campos para el registro de un nuevo usuario -->
                <input type="text" name="nombre" placeholder="Nombre" required>
                <input type="text" name="apellido" placeholder="Apellido" required>
                <input type="text" name="direccion" placeholder="Dirección" required>
                <input type="email" name="correo" placeholder="Correo electrónico" required>
                <input type="password" name="password" placeholder="password" required>
                <button type="submit">Crear usuario</button>
            </form>
            <p>¿Ya tienes una cuenta? <a href="{{ url_for('usuario.login') }}">Iniciar sesión</a></p>
        </div>

        <!-- Obtenemos el mensaje enviado desde el controlador -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <script>
                    //Guardamos el mensaje para utilizarlo en otro js
                    var mensaje_exitoso = "{{ messages[0] }}";
                </script>
                <script src="{{ url_for('static', filename='js/alerta_exitosa.js') }}"></script>
            {% endif %}
        {% endwith %}
    </body>
</html>

app/templates/ver_predicciones.html
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Predicción</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/ver_predicciones.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
    </head>
    <body>
        {% include 'partials/_navbar.html' %}

        <div class="container">
            {% for prediccion in predicciones %}
                <div class="card">
                    <img src="{{ prediccion.imagen_prediccion }}" alt="Imagen de la predicción">
                    <h3>Coyote: {{ prediccion.porcentaje_coyote }}%</h3>
                    <h3>Lobo: {{ prediccion.porcentaje_lobo }}%</h3>
                    <h3>Perro: {{ prediccion.porcentaje_perro }}%</h3>
                    <h3>Zorro: {{ prediccion.porcentaje_zorro }}%</h3>
                </div>
            {% endfor %}
        </div>
        
    </body>
    <script src="{{ url_for('static', filename='js/navbar.js') }}"></script>
</html>